### ISSUE TITLE
Website employee tab not scaling

### ISSUE THREAD

**Issue by MadisJu** [MadisJu/MadislolincWeb#8]
Bro, this not working, i am from phone so i cant post photos. Fix asap, TY.
//Probably CSS problematic because this was proge on my phone 📱

**Comment by OPuusalu** [comment]
Too bad

**Comment by MadisJu** [comment]
Too bad staart working

**Comment by MadisJu** [comment]
Bruh moment
https://user-images.githubusercontent.com/61630177/148922888-03b6f820-c4f6-4dac-9aec-9f24e356febf.mp4

**Comment by OPuusalu** [comment]
![RDT_20220110_1130562137571818173598484.jpg](https://user-images.githubusercontent.com/91115628/148923039-d788d8cf-3446-4dff-a8af-f3b9588da391.jpg)

**Comment by MadisJu** [comment]
I fixed it, in physics class, imagine not doing anything productive.
![IMG_20220111_130124.jpg](https://user-images.githubusercontent.com/61630177/148959824-e3f1922f-a1ff-4783-9e37-a27c28485e28.jpg)
